# ======================================= Learning configs ==================================
n_epoch: 7
batch_size: 64
test_batch_size: 64
lr: 0.00025
mi_lr: 0.001
loss_weights: 0.5
clip_gradient: 0.5
start_epoch: 0
weight_decay: 5e-4

  # ======================================= Print and snapshot configs ==================================
snapshot_pref: 
    /project/ag-jafra/Souptik/CMG_New/Experiments/CMG_trial1/Benchmarks/Retrieval_DCID_1/AVT/90k/MSCOCO/
print_freq: 1
eval_freq: 1


